# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  global:
      PYTHON: "C:\\conda"
      PYTHON_ARCH: "64"

  matrix:
      - PYTHON_VERSION: "2.7"
        CONDA_DEPENDENCIES: "numpy scipy matplotlib pyqt=5 jupyter setuptools nose pytest coverage pytest-cov cython"
        PIP_DEPENDENCIES: "numpydoc mock coveralls"
      - PYTHON_VERSION: "3.6"
        CONDA_DEPENDENCIES: "numpy scipy setuptools nose pytest coverage pytest-cov cython"
        PIP_DEPENDENCIES: "numpydoc coveralls"

platform:
    -x64

install:

  # Install OpenGL
  - "powershell ./make/install_opengl.ps1"

  # Install conda using ci-helpers. More information about ci-helpers can
  # be found here: https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "rm ci-helpers/test_env.py"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Switch to test environment
  - "activate test"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Skip using MESA for now since AppVeyor is unreliable with it
  - "SET VISPY_GL_LIB=%CD%\\opengl32.dll"

  # Update numpy to most recent
  # (numpy 1.14.3 is bad)
  - "conda update --yes numpy"

  # Install vispy
  - "python setup.py develop"
  - "python -c \"import vispy; print(vispy.sys_info())\""

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests (don't do examples because they are too slow)
  - "python make test unit"

on_success:
  - "coveralls"
